package dev.sagi.monotask.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF745B00)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFF4C310)
val onPrimaryContainerLight = Color(0xFF685100)
val secondaryLight = Color(0xFF0058BC)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF0070EB)
val onSecondaryContainerLight = Color(0xFFFEFCFF)
val tertiaryLight = Color(0xFF006C4B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF23D69A)
val onTertiaryContainerLight = Color(0xFF00573C)
val errorLight = Color(0xFFBA0628)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFDE2C3D)
val onErrorContainerLight = Color(0xFFFFFBFF)
val backgroundLight = Color(0xFFFFFAF7)
val onBackgroundLight = Color(0xFF1F1B11)
val surfaceLight = Color(0xFFFCF8F8)
val onSurfaceLight = Color(0xFF1C1B1B)
val surfaceVariantLight = Color(0xFFE0E3E3)
val onSurfaceVariantLight = Color(0xFF434748)
val outlineLight = Color(0xFF747878)
val outlineVariantLight = Color(0xFFC4C7C7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313030)
val inverseOnSurfaceLight = Color(0xFFF3F0EF)
val inversePrimaryLight = Color(0xFFF1C00A)
val surfaceDimLight = Color(0xFFDCD9D9)
val surfaceBrightLight = Color(0xFFFCF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F3F2)
val surfaceContainerLight = Color(0xFFF1EDEC)
val surfaceContainerHighLight = Color(0xFFEBE7E7)
val surfaceContainerHighestLight = Color(0xFFE5E2E1)

val primaryLightMediumContrast = Color(0xFF443400)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF866A00)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF003474)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF0069DD)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF003F2A)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF007D57)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF730014)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFD32236)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F1)
val onBackgroundLightMediumContrast = Color(0xFF1F1B11)
val surfaceLightMediumContrast = Color(0xFFFCF8F8)
val onSurfaceLightMediumContrast = Color(0xFF111111)
val surfaceVariantLightMediumContrast = Color(0xFFE0E3E3)
val onSurfaceVariantLightMediumContrast = Color(0xFF333737)
val outlineLightMediumContrast = Color(0xFF4F5354)
val outlineVariantLightMediumContrast = Color(0xFF6A6E6E)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF313030)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF3F0EF)
val inversePrimaryLightMediumContrast = Color(0xFFF1C00A)
val surfaceDimLightMediumContrast = Color(0xFFC9C6C5)
val surfaceBrightLightMediumContrast = Color(0xFFFCF8F8)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF6F3F2)
val surfaceContainerLightMediumContrast = Color(0xFFEBE7E7)
val surfaceContainerHighLightMediumContrast = Color(0xFFDFDCDB)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD4D1D0)

val primaryLightHighContrast = Color(0xFF382A00)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF5B4700)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF002A61)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF004698)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF003322)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF00543A)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF60000F)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF97001D)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF8F1)
val onBackgroundLightHighContrast = Color(0xFF1F1B11)
val surfaceLightHighContrast = Color(0xFFFCF8F8)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE0E3E3)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF292D2D)
val outlineVariantLightHighContrast = Color(0xFF464A4A)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF313030)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFF1C00A)
val surfaceDimLightHighContrast = Color(0xFFBBB8B8)
val surfaceBrightLightHighContrast = Color(0xFFFCF8F8)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF3F0EF)
val surfaceContainerLightHighContrast = Color(0xFFE5E2E1)
val surfaceContainerHighLightHighContrast = Color(0xFFD7D4D3)
val surfaceContainerHighestLightHighContrast = Color(0xFFC9C6C5)

val primaryDark = Color(0xFFFFE399)
val onPrimaryDark = Color(0xFF3D2F00)
val primaryContainerDark = Color(0xFFF4C310)
val onPrimaryContainerDark = Color(0xFF685100)
val secondaryDark = Color(0xFFADC6FF)
val onSecondaryDark = Color(0xFF002E69)
val secondaryContainerDark = Color(0xFF4B8EFF)
val onSecondaryContainerDark = Color(0xFF001435)
val tertiaryDark = Color(0xFF50F3B4)
val onTertiaryDark = Color(0xFF003825)
val tertiaryContainerDark = Color(0xFF23D69A)
val onTertiaryContainerDark = Color(0xFF00573C)
val errorDark = Color(0xFFFFB3B1)
val onErrorDark = Color(0xFF680011)
val errorContainerDark = Color(0xFFFF535A)
val onErrorContainerDark = Color(0xFF3B0006)
val backgroundDark = Color(0xFF171309)
val onBackgroundDark = Color(0xFFEBE1D0)
val surfaceDark = Color(0xFF131313)
val onSurfaceDark = Color(0xFFE5E2E1)
val surfaceVariantDark = Color(0xFF434748)
val onSurfaceVariantDark = Color(0xFFC4C7C7)
val outlineDark = Color(0xFF8E9192)
val outlineVariantDark = Color(0xFF434748)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2E1)
val inverseOnSurfaceDark = Color(0xFF313030)
val inversePrimaryDark = Color(0xFF745B00)
val surfaceDimDark = Color(0xFF131313)
val surfaceBrightDark = Color(0xFF3A3939)
val surfaceContainerLowestDark = Color(0xFF0E0E0E)
val surfaceContainerLowDark = Color(0xFF1C1B1B)
val surfaceContainerDark = Color(0xFF201F1F)
val surfaceContainerHighDark = Color(0xFF2A2A2A)
val surfaceContainerHighestDark = Color(0xFF353534)

val primaryDarkMediumContrast = Color(0xFFFFE399)
val onPrimaryDarkMediumContrast = Color(0xFF372A00)
val primaryContainerDarkMediumContrast = Color(0xFFF4C310)
val onPrimaryContainerDarkMediumContrast = Color(0xFF463600)
val secondaryDarkMediumContrast = Color(0xFFCFDCFF)
val onSecondaryDarkMediumContrast = Color(0xFF002454)
val secondaryContainerDarkMediumContrast = Color(0xFF4B8EFF)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFF55F7B8)
val onTertiaryDarkMediumContrast = Color(0xFF002C1C)
val tertiaryContainerDarkMediumContrast = Color(0xFF23D69A)
val onTertiaryContainerDarkMediumContrast = Color(0xFF003724)
val errorDarkMediumContrast = Color(0xFFFFD2D0)
val onErrorDarkMediumContrast = Color(0xFF54000C)
val errorContainerDarkMediumContrast = Color(0xFFFF535A)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF171309)
val onBackgroundDarkMediumContrast = Color(0xFFEBE1D0)
val surfaceDarkMediumContrast = Color(0xFF131313)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF434748)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDADDDD)
val outlineDarkMediumContrast = Color(0xFFAFB2B3)
val outlineVariantDarkMediumContrast = Color(0xFF8D9191)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE5E2E1)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2A2A2A)
val inversePrimaryDarkMediumContrast = Color(0xFF594500)
val surfaceDimDarkMediumContrast = Color(0xFF131313)
val surfaceBrightDarkMediumContrast = Color(0xFF454444)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF070707)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1E1D1D)
val surfaceContainerDarkMediumContrast = Color(0xFF282828)
val surfaceContainerHighDarkMediumContrast = Color(0xFF333232)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3E3D3D)

val primaryDarkHighContrast = Color(0xFFFFEFCA)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFF4C310)
val onPrimaryContainerDarkHighContrast = Color(0xFF1B1300)
val secondaryDarkHighContrast = Color(0xFFECEFFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFA7C3FF)
val onSecondaryContainerDarkHighContrast = Color(0xFF000A22)
val tertiaryDarkHighContrast = Color(0xFFB9FFDB)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF2FDC9F)
val onTertiaryContainerDarkHighContrast = Color(0xFF000E07)
val errorDarkHighContrast = Color(0xFFFFECEA)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFADAB)
val onErrorContainerDarkHighContrast = Color(0xFF220002)
val backgroundDarkHighContrast = Color(0xFF171309)
val onBackgroundDarkHighContrast = Color(0xFFEBE1D0)
val surfaceDarkHighContrast = Color(0xFF131313)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF434748)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEDF0F1)
val outlineVariantDarkHighContrast = Color(0xFFC0C3C3)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE5E2E1)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF594500)
val surfaceDimDarkHighContrast = Color(0xFF131313)
val surfaceBrightDarkHighContrast = Color(0xFF51504F)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF201F1F)
val surfaceContainerDarkHighContrast = Color(0xFF313030)
val surfaceContainerHighDarkHighContrast = Color(0xFF3C3B3B)
val surfaceContainerHighestDarkHighContrast = Color(0xFF474646)

val darkBlueLight = Color(0xFF00397C)
val onDarkBlueLight = Color(0xFFFFFFFF)
val darkBlueContainerLight = Color(0xFF004FA8)
val onDarkBlueContainerLight = Color(0xFFABC6FF)

val darkBlueLightMediumContrast = Color(0xFF003473)
val onDarkBlueLightMediumContrast = Color(0xFFFFFFFF)
val darkBlueContainerLightMediumContrast = Color(0xFF004FA8)
val onDarkBlueContainerLightMediumContrast = Color(0xFFF1F3FF)

val darkBlueLightHighContrast = Color(0xFF002A60)
val onDarkBlueLightHighContrast = Color(0xFFFFFFFF)
val darkBlueContainerLightHighContrast = Color(0xFF004697)
val onDarkBlueContainerLightHighContrast = Color(0xFFFFFFFF)

val darkBlueDark = Color(0xFFADC7FF)
val onDarkBlueDark = Color(0xFF002E68)
val darkBlueContainerDark = Color(0xFF004FA8)
val onDarkBlueContainerDark = Color(0xFFABC6FF)

val darkBlueDarkMediumContrast = Color(0xFFCEDCFF)
val onDarkBlueDarkMediumContrast = Color(0xFF002454)
val darkBlueContainerDarkMediumContrast = Color(0xFF5C90EC)
val onDarkBlueContainerDarkMediumContrast = Color(0xFF000000)

val darkBlueDarkHighContrast = Color(0xFFECEFFF)
val onDarkBlueDarkHighContrast = Color(0xFF000000)
val darkBlueContainerDarkHighContrast = Color(0xFFA6C3FF)
val onDarkBlueContainerDarkHighContrast = Color(0xFF000A22)


// ── MonoTask Custom Semantic Tokens ───────────────────
// These are NOT part of the M3 system
// brand-specific overlays used in custom composables only

val AceGold            = Color(0xFFFFD700) // Raw brand gold
val AceGoldGlow        = Color(0x40FFD700) // 25% alpha - glow ring on FocusCard
val AceGoldDim         = Color(0xFFCCAC00) // Darker gold - pressed states

val PenaltyRedGlow     = Color(0x33E63946) // 20% alpha - error container tint
val SuccessGreen       = Color(0xFF06D6A0) // Raw success color
val bonusGreen         = Color(0xCC39D540)
val penaltyRed         = Color(0xDDDE0F38)

val GlassSurface       = Color(0xCCFFFFFF) // 80% white - frosted card overlay (light)
val GlassSurfaceDark   = Color(0xCC1A1A2E) // 80% dark - frosted card overlay (dark)

val AeroShadow         = Color(0x1A000000) // 10% black - ambient shadow
val AeroShadowDeep     = Color(0x33000000) // 20% black - elevated card shadow


// ── Importance Tag Colors ────────────────────────────────────────
val ImportanceHighBackground   = Color(0xFFFFDDDD) // was 0xFFFFEDED
val ImportanceHighContent      = Color(0xFFB00020)

val ImportanceMediumBackground = Color(0xFFFFF0CC) // was 0xFFFFF8E1
val ImportanceMediumContent    = Color(0xFFF9A825)

val ImportanceLowBackground    = Color(0xFFD9EED9) // was 0xFFE8F5E9
val ImportanceLowContent       = Color(0xFF2E7D32)


// ── Custom Tag Colors ─────────────────────────────────────────────
val TagIndigoBackground   = Color(0xFFE8EAF6)
val TagIndigoContent      = Color(0xFF3949AB)

val TagTealBackground     = Color(0xFFE0F2F1)
val TagTealContent        = Color(0xFF00796B)

val TagPurpleBackground   = Color(0xFFF3E5F5)
val TagPurpleContent      = Color(0xFF7B1FA2)

val TagBlueBackground     = Color(0xFFE3F2FD)
val TagBlueContent        = Color(0xFF1565C0)

val TagCyanBackground     = Color(0xFFE0F7FA)
val TagCyanContent        = Color(0xFF0097A7)

val TagBrownBackground    = Color(0xFFEFEBE9)
val TagBrownContent       = Color(0xFF5D4037)

val TagBlueGreyBackground = Color(0xFFECEFF1)
val TagBlueGreyContent    = Color(0xFF455A64)

val TagLimeBackground     = Color(0xFFF9FBE7)
val TagLimeContent        = Color(0xFF827717)
